package com.example.Example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.client.RestTemplate;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class ExampleApplication {

	public static void main(String[] args){SpringApplication.run(ExampleApplication.class, args);}

	@Bean
	public RestTemplate restTemplate(){
		return new RestTemplate();
	}
}
